import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import type { Game } from '../comps/game-card'
import minLogo from '../public/logos/min.png'
import porLogo from '../public/logos/por.png'
import SingleDaySchedule from '../comps/single-day-schedule'

const GAME: Game = {
    date: new Date(),
    competition: 'NBA regular season',
    league: 'NBA',
    status: 'future',
    location: {
        arena: 'American Airlines Center',
        city: 'Oklahoma City, OK'
    },
    home: {
        abbreviation: 'POR',
        nickname: 'Trail Blazers',
        city: 'Portland',
        rank: 30,
        sport: 'Basketball',
        logo: porLogo,
        record: {
            wins: 82,
            losses: 82,
            ties: 82,
            division: 'West',
            divisionRank: 15
        }
    },
    away: {
        abbreviation: 'MIN',
        nickname: 'Timberwolves',
        city: 'Minnesota',
        rank: 30,
        sport: 'Basketball',
        logo: minLogo,
        record: {
            wins: 82,
            losses: 82,
            division: 'West',
            divisionRank: 15
        }
    }
}

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <SingleDaySchedule games={[GAME, GAME, GAME, GAME]} date={GAME.date} />
                <SingleDaySchedule games={[GAME, GAME, GAME, GAME]} date={GAME.date} />
                <SingleDaySchedule games={[GAME, GAME, GAME, GAME]} date={GAME.date} />
                <SingleDaySchedule games={[GAME, GAME, GAME, GAME]} date={GAME.date} />
            </main>
        </>
    )
}

export default Home
